######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 10 02:07:01 2015
######################################################################

TEMPLATE = app
TARGET = dyn_sizeof
DEPENDPATH += .
INCLUDEPATH += .

include(../../../src/util/util.pri)

# Input
SOURCES += main.cpp
LIBS+=-lrt
