######################################################################
# Automatically generated by qmake (2.01a) Mon Mar 23 17:20:02 2015
######################################################################

TEMPLATE = app
TARGET = pjpeg_serialize
DEPENDPATH += .
INCLUDEPATH += . ../../..

LIBS += -L../../../picojpeg -lpicojpeg

QT += gui

# Input
SOURCES += main.cpp
