######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 10 02:07:01 2015
######################################################################

TEMPLATE = app
TARGET = decode_good_file
DEPENDPATH += .
INCLUDEPATH += .

include(../../../src/common/common.pri)
include(../../../src/core/core.pri)
include(../../../src/util/util.pri)
include(../../../src/jpeg/jpeg.pri)

LIBS += -L../../../picojpeg -lpicojpeg
QT += gui

# Input
SOURCES += main.cpp

